# GET Request
GET http://localhost:3000/contacts


### GET Request by ID
GET http://localhost:3000/contacts/66fc4b279127d896559a94f7


### POST Request (Create a contact)
POST http://localhost:3000/contacts
Content-Type: application/json

{
    "firstName": "Jacobs",
    "lastName": "Philips",
    "email": "philip.jacobs@example.com",
    "favoriteColor": "white",
    "birthdate": "1970-09-02"
}


### PUT Request (Update a contact)
PUT http://localhost:3000/contacts/
Content-Type: application/json

{
  "firstName": "Samuel",
  "lastName": "Jacobs",
  "email": "samuel.jacobs@example.com",
  "favoriteColor": "Indigo",
  "birthdate": "1979-08-21"
}
